### ISSUE TITLE
Speech Access Token not Refreshing

### ISSUE THREAD

**Issue by Lord-Sheogorath** [ActiveNick/Unity-Text-to-Speech#5]
In SpeechManager.cs, you're getting the initial access token from the server and using that for the runtime of the application. Even though the Authentication class is re-authenticating in the background, the new access token is never being used in SpeechManager.cs (only the first token recieved).

**Comment by ActiveNick** [comment]
Hi there, this project only received limited testing so it's very likely that the code has some errors like this given that long running tests are more involved. The other reason is that I quickly moved away from this project since I worked with our internal Cognitive Services team to make sure that Unity would be supported.

Instead of using my code, I would invite you to look at the C# .NET SDK in Cognitive Services Speech since it includes compatible plugins for Unity and it's officially supported. I hope this helps.

**SDK**: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk
**Unity Quickstart**: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/from-microphone
